ALTER TABLE users ADD COLUMN IF NOT EXISTS aadhaar_card_number VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS pan_card_number VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS pf_account_number VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS esi_number VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS bank_account_number VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS ifsc_code VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS emergency_contact_name VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS emergency_contact_number VARCHAR(50);
